# Generated by Django 3.2.17 on 2023-02-17 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='prince',
            new_name='price',
        ),
    ]
